spring.application.name=demo
management.endpoints.web.exposure.include=*
management.info.env.enabled=
info.app.name=my cool app
info.app.description = crazy actuator property
info.app.version=1.0.0

spring.security.user.name=admin
spring.security.user.password=1234
#custom applicaton property
coach.name = shinchan